beliefs: [
  {
    id: "1"
    user_id: "user123"
    version: 1
    confidence_ratings: [
      {
        confidence_score: 0.8
        default: true
      }
    ]
    temporal_information: {
      start_time_millis_utc: 1609459200000
      end_time_millis_utc: 1609545600000
      is_active: true
    }
    sources: [
      {
        name: "Observation Result from Mental Clarity"
        type: OBSERVATION_CONTEXT
        observation_context_id: 2
      }
    ]
    content: [
      {
        raw_str: "If I drink water, I will have more mental clarity."
      }
    ]
    type: CAUSAL
    causal_belief: {
      intervention_id: 1
      intervention_name: "drinking water"
      observation_context_id: 2
      observation_context_name: "Mental Clarity"
    }
  },
  {
    id: "2"
    user_id: "user456"
    version: 1
    confidence_ratings: [
      {
        confidence_score: 0.9
        default: true
      }
    ]
    temporal_information: {
      start_time_millis_utc: 1609459200000
      end_time_millis_utc: 1609545600000
      is_active: true
    }
    sources: [
      {
        name: "Observation Result from Energy Levels"
        type: OBSERVATION_CONTEXT
        observation_context_id: 3
      }
    ]
    content: [
      {
        raw_str: "Daily exercise will increase overall energy levels and improve mood."
      }
    ]
    type: CAUSAL
    causal_belief: {
      intervention_id: 2
      intervention_name: "exercise"
      observation_context_id: 3
      observation_context_name: "Energy Levels"
    }
  },
  {
    id: "3"
    user_id: "user789"
    version: 1
    confidence_ratings: [
      {
        confidence_score: 0.7
        default: true
      }
    ]
    temporal_information: {
      start_time_millis_utc: 1609459200000
      end_time_millis_utc: 1609545600000
      is_active: true
    }
    sources: [
      {
        name: "Plato's Republic"
        type: AUTHORITY
        resources: [
          {
            name: "Plato's Republic"
            type: BOOK
          }
        ]
      }
    ]
    content: [
      {
        raw_str: "I believe that justice is the interest of the stronger."
      }
    ]
    type: STATEMENT
  }
]
