// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: proto/models/dialectic.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Add STATUS enum definition
type STATUS int32

const (
	STATUS_STATUS_INVALID         STATUS = 0
	STATUS_STATUS_PENDING_ANSWER  STATUS = 1
	STATUS_STATUS_ANSWERED        STATUS = 2
	STATUS_STATUS_BELIEFS_UPDATED STATUS = 3
)

// Enum value maps for STATUS.
var (
	STATUS_name = map[int32]string{
		0: "STATUS_INVALID",
		1: "STATUS_PENDING_ANSWER",
		2: "STATUS_ANSWERED",
		3: "STATUS_BELIEFS_UPDATED",
	}
	STATUS_value = map[string]int32{
		"STATUS_INVALID":         0,
		"STATUS_PENDING_ANSWER":  1,
		"STATUS_ANSWERED":        2,
		"STATUS_BELIEFS_UPDATED": 3,
	}
)

func (x STATUS) Enum() *STATUS {
	p := new(STATUS)
	*p = x
	return p
}

func (x STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_models_dialectic_proto_enumTypes[0].Descriptor()
}

func (STATUS) Type() protoreflect.EnumType {
	return &file_proto_models_dialectic_proto_enumTypes[0]
}

func (x STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use STATUS.Descriptor instead.
func (STATUS) EnumDescriptor() ([]byte, []int) {
	return file_proto_models_dialectic_proto_rawDescGZIP(), []int{0}
}

// The Dialectic Type informs the "strategy" of how the
// agent will attempt to generate questions and interpret beliefs
// from the user's responses.
type DialecticType int32

const (
	DialecticType_INVALID             DialecticType = 0
	DialecticType_DEFAULT             DialecticType = 1
	DialecticType_HEGELIAN            DialecticType = 2
	DialecticType_SLEEP_DIET_EXERCISE DialecticType = 3
)

// Enum value maps for DialecticType.
var (
	DialecticType_name = map[int32]string{
		0: "INVALID",
		1: "DEFAULT",
		2: "HEGELIAN",
		3: "SLEEP_DIET_EXERCISE",
	}
	DialecticType_value = map[string]int32{
		"INVALID":             0,
		"DEFAULT":             1,
		"HEGELIAN":            2,
		"SLEEP_DIET_EXERCISE": 3,
	}
)

func (x DialecticType) Enum() *DialecticType {
	p := new(DialecticType)
	*p = x
	return p
}

func (x DialecticType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DialecticType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_models_dialectic_proto_enumTypes[1].Descriptor()
}

func (DialecticType) Type() protoreflect.EnumType {
	return &file_proto_models_dialectic_proto_enumTypes[1]
}

func (x DialecticType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DialecticType.Descriptor instead.
func (DialecticType) EnumDescriptor() ([]byte, []int) {
	return file_proto_models_dialectic_proto_rawDescGZIP(), []int{1}
}

type DialecticalInteraction_InteractionType int32

const (
	DialecticalInteraction_INTERACTION_TYPE_INVALID DialecticalInteraction_InteractionType = 0
	DialecticalInteraction_QUESTION_ANSWER          DialecticalInteraction_InteractionType = 1
	DialecticalInteraction_HYPOTHESIS_EVIDENCE      DialecticalInteraction_InteractionType = 2
	DialecticalInteraction_ACTION_OUTCOME           DialecticalInteraction_InteractionType = 3
)

// Enum value maps for DialecticalInteraction_InteractionType.
var (
	DialecticalInteraction_InteractionType_name = map[int32]string{
		0: "INTERACTION_TYPE_INVALID",
		1: "QUESTION_ANSWER",
		2: "HYPOTHESIS_EVIDENCE",
		3: "ACTION_OUTCOME",
	}
	DialecticalInteraction_InteractionType_value = map[string]int32{
		"INTERACTION_TYPE_INVALID": 0,
		"QUESTION_ANSWER":          1,
		"HYPOTHESIS_EVIDENCE":      2,
		"ACTION_OUTCOME":           3,
	}
)

func (x DialecticalInteraction_InteractionType) Enum() *DialecticalInteraction_InteractionType {
	p := new(DialecticalInteraction_InteractionType)
	*p = x
	return p
}

func (x DialecticalInteraction_InteractionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DialecticalInteraction_InteractionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_models_dialectic_proto_enumTypes[2].Descriptor()
}

func (DialecticalInteraction_InteractionType) Type() protoreflect.EnumType {
	return &file_proto_models_dialectic_proto_enumTypes[2]
}

func (x DialecticalInteraction_InteractionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DialecticalInteraction_InteractionType.Descriptor instead.
func (DialecticalInteraction_InteractionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_models_dialectic_proto_rawDescGZIP(), []int{5, 0}
}

// Labels the system that is driving the agent's behavior.
// This may include generating the question, synthesizing
// the user's answers into beliefs, and then synthesizing
// the user's supposed beliefs into a belief system
// that can be used for further generations.
type Agent_AgentType int32

const (
	Agent_AGENT_TYPE_INVALID    Agent_AgentType = 0 // Invalid agent type.
	Agent_AGENT_TYPE_GPT_LATEST Agent_AgentType = 1 // Latest GPT model.
)

// Enum value maps for Agent_AgentType.
var (
	Agent_AgentType_name = map[int32]string{
		0: "AGENT_TYPE_INVALID",
		1: "AGENT_TYPE_GPT_LATEST",
	}
	Agent_AgentType_value = map[string]int32{
		"AGENT_TYPE_INVALID":    0,
		"AGENT_TYPE_GPT_LATEST": 1,
	}
)

func (x Agent_AgentType) Enum() *Agent_AgentType {
	p := new(Agent_AgentType)
	*p = x
	return p
}

func (x Agent_AgentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Agent_AgentType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_models_dialectic_proto_enumTypes[3].Descriptor()
}

func (Agent_AgentType) Type() protoreflect.EnumType {
	return &file_proto_models_dialectic_proto_enumTypes[3]
}

func (x Agent_AgentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Agent_AgentType.Descriptor instead.
func (Agent_AgentType) EnumDescriptor() ([]byte, []int) {
	return file_proto_models_dialectic_proto_rawDescGZIP(), []int{6, 0}
}

// Question represents a request for information
type Question struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Question           string `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	CreatedAtMillisUtc int64  `protobuf:"varint,2,opt,name=created_at_millis_utc,json=createdAtMillisUtc,proto3" json:"created_at_millis_utc,omitempty"`
}

func (x *Question) Reset() {
	*x = Question{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_models_dialectic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_dialectic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_proto_models_dialectic_proto_rawDescGZIP(), []int{0}
}

func (x *Question) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Question) GetCreatedAtMillisUtc() int64 {
	if x != nil {
		return x.CreatedAtMillisUtc
	}
	return 0
}

// UserAnswer represents a response to a question
type UserAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserAnswer         string `protobuf:"bytes,1,opt,name=user_answer,json=userAnswer,proto3" json:"user_answer,omitempty"`
	CreatedAtMillisUtc int64  `protobuf:"varint,2,opt,name=created_at_millis_utc,json=createdAtMillisUtc,proto3" json:"created_at_millis_utc,omitempty"`
}

func (x *UserAnswer) Reset() {
	*x = UserAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_models_dialectic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAnswer) ProtoMessage() {}

func (x *UserAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_dialectic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAnswer.ProtoReflect.Descriptor instead.
func (*UserAnswer) Descriptor() ([]byte, []int) {
	return file_proto_models_dialectic_proto_rawDescGZIP(), []int{1}
}

func (x *UserAnswer) GetUserAnswer() string {
	if x != nil {
		return x.UserAnswer
	}
	return ""
}

func (x *UserAnswer) GetCreatedAtMillisUtc() int64 {
	if x != nil {
		return x.CreatedAtMillisUtc
	}
	return 0
}

// Question-Answer interaction for extracting beliefs
type QuestionAnswerInteraction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Question           *Question   `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Answer             *UserAnswer `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	ExtractedBeliefs   []*Belief   `protobuf:"bytes,3,rep,name=extracted_beliefs,json=extractedBeliefs,proto3" json:"extracted_beliefs,omitempty"`
	UpdatedAtMillisUtc int64       `protobuf:"varint,4,opt,name=updated_at_millis_utc,json=updatedAtMillisUtc,proto3" json:"updated_at_millis_utc,omitempty"`
}

func (x *QuestionAnswerInteraction) Reset() {
	*x = QuestionAnswerInteraction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_models_dialectic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuestionAnswerInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionAnswerInteraction) ProtoMessage() {}

func (x *QuestionAnswerInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_dialectic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionAnswerInteraction.ProtoReflect.Descriptor instead.
func (*QuestionAnswerInteraction) Descriptor() ([]byte, []int) {
	return file_proto_models_dialectic_proto_rawDescGZIP(), []int{2}
}

func (x *QuestionAnswerInteraction) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

func (x *QuestionAnswerInteraction) GetAnswer() *UserAnswer {
	if x != nil {
		return x.Answer
	}
	return nil
}

func (x *QuestionAnswerInteraction) GetExtractedBeliefs() []*Belief {
	if x != nil {
		return x.ExtractedBeliefs
	}
	return nil
}

func (x *QuestionAnswerInteraction) GetUpdatedAtMillisUtc() int64 {
	if x != nil {
		return x.UpdatedAtMillisUtc
	}
	return 0
}

// Hypothesis-Evidence interaction for testing beliefs
type HypothesisEvidenceInteraction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hypothesis         string    `protobuf:"bytes,1,opt,name=hypothesis,proto3" json:"hypothesis,omitempty"`
	Evidence           string    `protobuf:"bytes,2,opt,name=evidence,proto3" json:"evidence,omitempty"`
	IsCounterfactual   bool      `protobuf:"varint,3,opt,name=is_counterfactual,json=isCounterfactual,proto3" json:"is_counterfactual,omitempty"` // Indicates if this is counterfactual evidence
	UpdatedBeliefs     []*Belief `protobuf:"bytes,4,rep,name=updated_beliefs,json=updatedBeliefs,proto3" json:"updated_beliefs,omitempty"`
	UpdatedAtMillisUtc int64     `protobuf:"varint,5,opt,name=updated_at_millis_utc,json=updatedAtMillisUtc,proto3" json:"updated_at_millis_utc,omitempty"`
}

func (x *HypothesisEvidenceInteraction) Reset() {
	*x = HypothesisEvidenceInteraction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_models_dialectic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HypothesisEvidenceInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HypothesisEvidenceInteraction) ProtoMessage() {}

func (x *HypothesisEvidenceInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_dialectic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HypothesisEvidenceInteraction.ProtoReflect.Descriptor instead.
func (*HypothesisEvidenceInteraction) Descriptor() ([]byte, []int) {
	return file_proto_models_dialectic_proto_rawDescGZIP(), []int{3}
}

func (x *HypothesisEvidenceInteraction) GetHypothesis() string {
	if x != nil {
		return x.Hypothesis
	}
	return ""
}

func (x *HypothesisEvidenceInteraction) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

func (x *HypothesisEvidenceInteraction) GetIsCounterfactual() bool {
	if x != nil {
		return x.IsCounterfactual
	}
	return false
}

func (x *HypothesisEvidenceInteraction) GetUpdatedBeliefs() []*Belief {
	if x != nil {
		return x.UpdatedBeliefs
	}
	return nil
}

func (x *HypothesisEvidenceInteraction) GetUpdatedAtMillisUtc() int64 {
	if x != nil {
		return x.UpdatedAtMillisUtc
	}
	return 0
}

// Action-Outcome interaction for testing causal beliefs
type ActionOutcomeInteraction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action             string    `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Outcome            string    `protobuf:"bytes,2,opt,name=outcome,proto3" json:"outcome,omitempty"`
	UpdatedBeliefs     []*Belief `protobuf:"bytes,3,rep,name=updated_beliefs,json=updatedBeliefs,proto3" json:"updated_beliefs,omitempty"`
	UpdatedAtMillisUtc int64     `protobuf:"varint,4,opt,name=updated_at_millis_utc,json=updatedAtMillisUtc,proto3" json:"updated_at_millis_utc,omitempty"`
}

func (x *ActionOutcomeInteraction) Reset() {
	*x = ActionOutcomeInteraction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_models_dialectic_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionOutcomeInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionOutcomeInteraction) ProtoMessage() {}

func (x *ActionOutcomeInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_dialectic_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionOutcomeInteraction.ProtoReflect.Descriptor instead.
func (*ActionOutcomeInteraction) Descriptor() ([]byte, []int) {
	return file_proto_models_dialectic_proto_rawDescGZIP(), []int{4}
}

func (x *ActionOutcomeInteraction) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ActionOutcomeInteraction) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *ActionOutcomeInteraction) GetUpdatedBeliefs() []*Belief {
	if x != nil {
		return x.UpdatedBeliefs
	}
	return nil
}

func (x *ActionOutcomeInteraction) GetUpdatedAtMillisUtc() int64 {
	if x != nil {
		return x.UpdatedAtMillisUtc
	}
	return 0
}

// Update DialecticalInteraction to use the new types
type DialecticalInteraction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type DialecticalInteraction_InteractionType `protobuf:"varint,1,opt,name=type,proto3,enum=DialecticalInteraction_InteractionType" json:"type,omitempty"`
	// Types that are assignable to Interaction:
	//
	//	*DialecticalInteraction_QuestionAnswer
	//	*DialecticalInteraction_HypothesisEvidence
	//	*DialecticalInteraction_ActionOutcome
	Interaction isDialecticalInteraction_Interaction `protobuf_oneof:"interaction"`
	Status      STATUS                               `protobuf:"varint,5,opt,name=status,proto3,enum=STATUS" json:"status,omitempty"`
}

func (x *DialecticalInteraction) Reset() {
	*x = DialecticalInteraction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_models_dialectic_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialecticalInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialecticalInteraction) ProtoMessage() {}

func (x *DialecticalInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_dialectic_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialecticalInteraction.ProtoReflect.Descriptor instead.
func (*DialecticalInteraction) Descriptor() ([]byte, []int) {
	return file_proto_models_dialectic_proto_rawDescGZIP(), []int{5}
}

func (x *DialecticalInteraction) GetType() DialecticalInteraction_InteractionType {
	if x != nil {
		return x.Type
	}
	return DialecticalInteraction_INTERACTION_TYPE_INVALID
}

func (m *DialecticalInteraction) GetInteraction() isDialecticalInteraction_Interaction {
	if m != nil {
		return m.Interaction
	}
	return nil
}

func (x *DialecticalInteraction) GetQuestionAnswer() *QuestionAnswerInteraction {
	if x, ok := x.GetInteraction().(*DialecticalInteraction_QuestionAnswer); ok {
		return x.QuestionAnswer
	}
	return nil
}

func (x *DialecticalInteraction) GetHypothesisEvidence() *HypothesisEvidenceInteraction {
	if x, ok := x.GetInteraction().(*DialecticalInteraction_HypothesisEvidence); ok {
		return x.HypothesisEvidence
	}
	return nil
}

func (x *DialecticalInteraction) GetActionOutcome() *ActionOutcomeInteraction {
	if x, ok := x.GetInteraction().(*DialecticalInteraction_ActionOutcome); ok {
		return x.ActionOutcome
	}
	return nil
}

func (x *DialecticalInteraction) GetStatus() STATUS {
	if x != nil {
		return x.Status
	}
	return STATUS_STATUS_INVALID
}

type isDialecticalInteraction_Interaction interface {
	isDialecticalInteraction_Interaction()
}

type DialecticalInteraction_QuestionAnswer struct {
	QuestionAnswer *QuestionAnswerInteraction `protobuf:"bytes,2,opt,name=question_answer,json=questionAnswer,proto3,oneof"`
}

type DialecticalInteraction_HypothesisEvidence struct {
	HypothesisEvidence *HypothesisEvidenceInteraction `protobuf:"bytes,3,opt,name=hypothesis_evidence,json=hypothesisEvidence,proto3,oneof"`
}

type DialecticalInteraction_ActionOutcome struct {
	ActionOutcome *ActionOutcomeInteraction `protobuf:"bytes,4,opt,name=action_outcome,json=actionOutcome,proto3,oneof"`
}

func (*DialecticalInteraction_QuestionAnswer) isDialecticalInteraction_Interaction() {}

func (*DialecticalInteraction_HypothesisEvidence) isDialecticalInteraction_Interaction() {}

func (*DialecticalInteraction_ActionOutcome) isDialecticalInteraction_Interaction() {}

// The agent represents information about what underlying
// system or user is responsible for interacting with the
// user throughout the dialectic. This is intended to
// be some AI system (e.g., LLM) but may evolve to be a human
// user in the future.
type Agent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentType     Agent_AgentType `protobuf:"varint,1,opt,name=agent_type,json=agentType,proto3,enum=Agent_AgentType" json:"agent_type,omitempty"`           // The type of the agent.
	DialecticType DialecticType   `protobuf:"varint,2,opt,name=dialectic_type,json=dialecticType,proto3,enum=DialecticType" json:"dialectic_type,omitempty"` // The dialectic strategy used by the agent.
}

func (x *Agent) Reset() {
	*x = Agent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_models_dialectic_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_dialectic_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_proto_models_dialectic_proto_rawDescGZIP(), []int{6}
}

func (x *Agent) GetAgentType() Agent_AgentType {
	if x != nil {
		return x.AgentType
	}
	return Agent_AGENT_TYPE_INVALID
}

func (x *Agent) GetDialecticType() DialecticType {
	if x != nil {
		return x.DialecticType
	}
	return DialecticType_INVALID
}

// The dialectic can be seen as a session that gets created
// and presents a user with a series of questions designed to
// determine and clarify the user's beliefs. The beliefs produced
// as part of the dialectic may or may not be fed into the user's
// underlying belief system.
type Dialectic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Unique identifier for the dialectic.
	// The user who the dialectic is "serving" in the sense
	// of who questions are being presented to and whose answers
	// represent the beliefs.
	SelfModelId      string                    `protobuf:"bytes,2,opt,name=self_model_id,json=selfModelId,proto3" json:"self_model_id,omitempty"`
	Agent            *Agent                    `protobuf:"bytes,3,opt,name=agent,proto3" json:"agent,omitempty"`                                               // The agent conducting the dialectic.
	UserInteractions []*DialecticalInteraction `protobuf:"bytes,4,rep,name=user_interactions,json=userInteractions,proto3" json:"user_interactions,omitempty"` // Interactions within the dialectic.
	BeliefSystem     *BeliefSystem             `protobuf:"bytes,5,opt,name=belief_system,json=beliefSystem,proto3" json:"belief_system,omitempty"`             // Add this line
	Analysis         *BeliefAnalysis           `protobuf:"bytes,6,opt,name=analysis,proto3" json:"analysis,omitempty"`                                         // Add this line
}

func (x *Dialectic) Reset() {
	*x = Dialectic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_models_dialectic_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dialectic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dialectic) ProtoMessage() {}

func (x *Dialectic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_dialectic_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dialectic.ProtoReflect.Descriptor instead.
func (*Dialectic) Descriptor() ([]byte, []int) {
	return file_proto_models_dialectic_proto_rawDescGZIP(), []int{7}
}

func (x *Dialectic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Dialectic) GetSelfModelId() string {
	if x != nil {
		return x.SelfModelId
	}
	return ""
}

func (x *Dialectic) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *Dialectic) GetUserInteractions() []*DialecticalInteraction {
	if x != nil {
		return x.UserInteractions
	}
	return nil
}

func (x *Dialectic) GetBeliefSystem() *BeliefSystem {
	if x != nil {
		return x.BeliefSystem
	}
	return nil
}

func (x *Dialectic) GetAnalysis() *BeliefAnalysis {
	if x != nil {
		return x.Analysis
	}
	return nil
}

// Add a new message for the analysis
type BeliefAnalysis struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coherence       float32  `protobuf:"fixed32,1,opt,name=coherence,proto3" json:"coherence,omitempty"`
	Consistency     float32  `protobuf:"fixed32,2,opt,name=consistency,proto3" json:"consistency,omitempty"`
	Falsifiability  float32  `protobuf:"fixed32,3,opt,name=falsifiability,proto3" json:"falsifiability,omitempty"`
	OverallScore    float32  `protobuf:"fixed32,4,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	Feedback        string   `protobuf:"bytes,5,opt,name=feedback,proto3" json:"feedback,omitempty"`
	Recommendations []string `protobuf:"bytes,6,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	VerifiedBeliefs []string `protobuf:"bytes,7,rep,name=verified_beliefs,json=verifiedBeliefs,proto3" json:"verified_beliefs,omitempty"`
}

func (x *BeliefAnalysis) Reset() {
	*x = BeliefAnalysis{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_models_dialectic_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeliefAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeliefAnalysis) ProtoMessage() {}

func (x *BeliefAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_dialectic_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeliefAnalysis.ProtoReflect.Descriptor instead.
func (*BeliefAnalysis) Descriptor() ([]byte, []int) {
	return file_proto_models_dialectic_proto_rawDescGZIP(), []int{8}
}

func (x *BeliefAnalysis) GetCoherence() float32 {
	if x != nil {
		return x.Coherence
	}
	return 0
}

func (x *BeliefAnalysis) GetConsistency() float32 {
	if x != nil {
		return x.Consistency
	}
	return 0
}

func (x *BeliefAnalysis) GetFalsifiability() float32 {
	if x != nil {
		return x.Falsifiability
	}
	return 0
}

func (x *BeliefAnalysis) GetOverallScore() float32 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *BeliefAnalysis) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *BeliefAnalysis) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *BeliefAnalysis) GetVerifiedBeliefs() []string {
	if x != nil {
		return x.VerifiedBeliefs
	}
	return nil
}

var File_proto_models_dialectic_proto protoreflect.FileDescriptor

var file_proto_models_dialectic_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x64,
	0x69, 0x61, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x62, 0x65, 0x6c,
	0x69, 0x65, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x08, 0x51, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x15, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x5f, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x5f, 0x75, 0x74, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x12, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x4d, 0x69, 0x6c, 0x6c,
	0x69, 0x73, 0x55, 0x74, 0x63, 0x22, 0x60, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x15, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x5f, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x5f, 0x75, 0x74, 0x63, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x12, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x4d, 0x69,
	0x6c, 0x6c, 0x69, 0x73, 0x55, 0x74, 0x63, 0x22, 0xd0, 0x01, 0x0a, 0x19, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x06,
	0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x12, 0x34, 0x0a, 0x11, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x62,
	0x65, 0x6c, 0x69, 0x65, 0x66, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x42,
	0x65, 0x6c, 0x69, 0x65, 0x66, 0x52, 0x10, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x65, 0x64,
	0x42, 0x65, 0x6c, 0x69, 0x65, 0x66, 0x73, 0x12, 0x31, 0x0a, 0x15, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x5f, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x5f, 0x75, 0x74, 0x63,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x55, 0x74, 0x63, 0x22, 0xed, 0x01, 0x0a, 0x1d, 0x48,
	0x79, 0x70, 0x6f, 0x74, 0x68, 0x65, 0x73, 0x69, 0x73, 0x45, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63,
	0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a,
	0x68, 0x79, 0x70, 0x6f, 0x74, 0x68, 0x65, 0x73, 0x69, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x68, 0x79, 0x70, 0x6f, 0x74, 0x68, 0x65, 0x73, 0x69, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x65, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x69, 0x73, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x10, 0x69, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x74, 0x75, 0x61, 0x6c, 0x12, 0x30, 0x0a, 0x0f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x62, 0x65, 0x6c, 0x69, 0x65, 0x66, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07,
	0x2e, 0x42, 0x65, 0x6c, 0x69, 0x65, 0x66, 0x52, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x42, 0x65, 0x6c, 0x69, 0x65, 0x66, 0x73, 0x12, 0x31, 0x0a, 0x15, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x5f, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x5f, 0x75, 0x74, 0x63,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x55, 0x74, 0x63, 0x22, 0xb1, 0x01, 0x0a, 0x18, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x0f, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x65, 0x6c, 0x69, 0x65, 0x66, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x07, 0x2e, 0x42, 0x65, 0x6c, 0x69, 0x65, 0x66, 0x52, 0x0e, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x42, 0x65, 0x6c, 0x69, 0x65, 0x66, 0x73, 0x12, 0x31, 0x0a, 0x15, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x5f, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73,
	0x5f, 0x75, 0x74, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x55, 0x74, 0x63, 0x22, 0xd6,
	0x03, 0x0a, 0x16, 0x44, 0x69, 0x61, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3b, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x63, 0x61, 0x6c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x45, 0x0a, 0x0f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0e, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x51, 0x0a,
	0x13, 0x68, 0x79, 0x70, 0x6f, 0x74, 0x68, 0x65, 0x73, 0x69, 0x73, 0x5f, 0x65, 0x76, 0x69, 0x64,
	0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x48, 0x79, 0x70,
	0x6f, 0x74, 0x68, 0x65, 0x73, 0x69, 0x73, 0x45, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x12, 0x68, 0x79,
	0x70, 0x6f, 0x74, 0x68, 0x65, 0x73, 0x69, 0x73, 0x45, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65,
	0x12, 0x42, 0x0a, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6f, 0x75, 0x74, 0x63, 0x6f,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x75, 0x74,
	0x63, 0x6f, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x71, 0x0a, 0x0f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x49, 0x4e, 0x54, 0x45,
	0x52, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x4e, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x51, 0x55, 0x45, 0x53, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x41, 0x4e, 0x53, 0x57, 0x45, 0x52, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x48,
	0x59, 0x50, 0x4f, 0x54, 0x48, 0x45, 0x53, 0x49, 0x53, 0x5f, 0x45, 0x56, 0x49, 0x44, 0x45, 0x4e,
	0x43, 0x45, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4f,
	0x55, 0x54, 0x43, 0x4f, 0x4d, 0x45, 0x10, 0x03, 0x42, 0x0d, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xaf, 0x01, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x12, 0x2f, 0x0a, 0x0a, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x35, 0x0a, 0x0e, 0x64, 0x69, 0x61, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x63, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x44, 0x69, 0x61,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0d, 0x64, 0x69, 0x61, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3e, 0x0a, 0x09, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x19,
	0x0a, 0x15, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x50, 0x54,
	0x5f, 0x4c, 0x41, 0x54, 0x45, 0x53, 0x54, 0x10, 0x01, 0x22, 0x84, 0x02, 0x0a, 0x09, 0x44, 0x69,
	0x61, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x65, 0x6c, 0x66, 0x5f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x73, 0x65, 0x6c, 0x66, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x05, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x44, 0x0a, 0x11, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x63,
	0x61, 0x6c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x10, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x32, 0x0a, 0x0d, 0x62, 0x65, 0x6c, 0x69, 0x65, 0x66, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x65, 0x6c, 0x69, 0x65, 0x66, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x52, 0x0c, 0x62, 0x65, 0x6c, 0x69, 0x65, 0x66, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x12, 0x2b, 0x0a, 0x08, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x42, 0x65, 0x6c, 0x69, 0x65, 0x66, 0x41, 0x6e,
	0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x08, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73,
	0x22, 0x8e, 0x02, 0x0a, 0x0e, 0x42, 0x65, 0x6c, 0x69, 0x65, 0x66, 0x41, 0x6e, 0x61, 0x6c, 0x79,
	0x73, 0x69, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x68, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x63, 0x6f, 0x68, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x63, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x66, 0x61, 0x6c, 0x73, 0x69, 0x66, 0x69, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x66, 0x61, 0x6c,
	0x73, 0x69, 0x66, 0x69, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x6f,
	0x76, 0x65, 0x72, 0x61, 0x6c, 0x6c, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0c, 0x6f, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x28, 0x0a, 0x0f,
	0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x5f, 0x62, 0x65, 0x6c, 0x69, 0x65, 0x66, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x42, 0x65, 0x6c, 0x69, 0x65, 0x66,
	0x73, 0x2a, 0x68, 0x0a, 0x06, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x12, 0x12, 0x0a, 0x0e, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12,
	0x19, 0x0a, 0x15, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e,
	0x47, 0x5f, 0x41, 0x4e, 0x53, 0x57, 0x45, 0x52, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x4e, 0x53, 0x57, 0x45, 0x52, 0x45, 0x44, 0x10, 0x02, 0x12,
	0x1a, 0x0a, 0x16, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x42, 0x45, 0x4c, 0x49, 0x45, 0x46,
	0x53, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x44, 0x10, 0x03, 0x2a, 0x50, 0x0a, 0x0d, 0x44,
	0x69, 0x61, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x46,
	0x41, 0x55, 0x4c, 0x54, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x48, 0x45, 0x47, 0x45, 0x4c, 0x49,
	0x41, 0x4e, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x4c, 0x45, 0x45, 0x50, 0x5f, 0x44, 0x49,
	0x45, 0x54, 0x5f, 0x45, 0x58, 0x45, 0x52, 0x43, 0x49, 0x53, 0x45, 0x10, 0x03, 0x42, 0x20, 0x5a,
	0x1e, 0x65, 0x70, 0x69, 0x73, 0x74, 0x65, 0x6d, 0x69, 0x63, 0x2d, 0x6d, 0x65, 0x2d, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_models_dialectic_proto_rawDescOnce sync.Once
	file_proto_models_dialectic_proto_rawDescData = file_proto_models_dialectic_proto_rawDesc
)

func file_proto_models_dialectic_proto_rawDescGZIP() []byte {
	file_proto_models_dialectic_proto_rawDescOnce.Do(func() {
		file_proto_models_dialectic_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_models_dialectic_proto_rawDescData)
	})
	return file_proto_models_dialectic_proto_rawDescData
}

var file_proto_models_dialectic_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_models_dialectic_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_models_dialectic_proto_goTypes = []any{
	(STATUS)(0),        // 0: STATUS
	(DialecticType)(0), // 1: DialecticType
	(DialecticalInteraction_InteractionType)(0), // 2: DialecticalInteraction.InteractionType
	(Agent_AgentType)(0),                        // 3: Agent.AgentType
	(*Question)(nil),                            // 4: Question
	(*UserAnswer)(nil),                          // 5: UserAnswer
	(*QuestionAnswerInteraction)(nil),           // 6: QuestionAnswerInteraction
	(*HypothesisEvidenceInteraction)(nil),       // 7: HypothesisEvidenceInteraction
	(*ActionOutcomeInteraction)(nil),            // 8: ActionOutcomeInteraction
	(*DialecticalInteraction)(nil),              // 9: DialecticalInteraction
	(*Agent)(nil),                               // 10: Agent
	(*Dialectic)(nil),                           // 11: Dialectic
	(*BeliefAnalysis)(nil),                      // 12: BeliefAnalysis
	(*Belief)(nil),                              // 13: Belief
	(*BeliefSystem)(nil),                        // 14: BeliefSystem
}
var file_proto_models_dialectic_proto_depIdxs = []int32{
	4,  // 0: QuestionAnswerInteraction.question:type_name -> Question
	5,  // 1: QuestionAnswerInteraction.answer:type_name -> UserAnswer
	13, // 2: QuestionAnswerInteraction.extracted_beliefs:type_name -> Belief
	13, // 3: HypothesisEvidenceInteraction.updated_beliefs:type_name -> Belief
	13, // 4: ActionOutcomeInteraction.updated_beliefs:type_name -> Belief
	2,  // 5: DialecticalInteraction.type:type_name -> DialecticalInteraction.InteractionType
	6,  // 6: DialecticalInteraction.question_answer:type_name -> QuestionAnswerInteraction
	7,  // 7: DialecticalInteraction.hypothesis_evidence:type_name -> HypothesisEvidenceInteraction
	8,  // 8: DialecticalInteraction.action_outcome:type_name -> ActionOutcomeInteraction
	0,  // 9: DialecticalInteraction.status:type_name -> STATUS
	3,  // 10: Agent.agent_type:type_name -> Agent.AgentType
	1,  // 11: Agent.dialectic_type:type_name -> DialecticType
	10, // 12: Dialectic.agent:type_name -> Agent
	9,  // 13: Dialectic.user_interactions:type_name -> DialecticalInteraction
	14, // 14: Dialectic.belief_system:type_name -> BeliefSystem
	12, // 15: Dialectic.analysis:type_name -> BeliefAnalysis
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_models_dialectic_proto_init() }
func file_proto_models_dialectic_proto_init() {
	if File_proto_models_dialectic_proto != nil {
		return
	}
	file_proto_models_beliefs_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_models_dialectic_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Question); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_models_dialectic_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UserAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_models_dialectic_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*QuestionAnswerInteraction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_models_dialectic_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*HypothesisEvidenceInteraction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_models_dialectic_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ActionOutcomeInteraction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_models_dialectic_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DialecticalInteraction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_models_dialectic_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Agent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_models_dialectic_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Dialectic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_models_dialectic_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*BeliefAnalysis); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_models_dialectic_proto_msgTypes[5].OneofWrappers = []any{
		(*DialecticalInteraction_QuestionAnswer)(nil),
		(*DialecticalInteraction_HypothesisEvidence)(nil),
		(*DialecticalInteraction_ActionOutcome)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_models_dialectic_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_models_dialectic_proto_goTypes,
		DependencyIndexes: file_proto_models_dialectic_proto_depIdxs,
		EnumInfos:         file_proto_models_dialectic_proto_enumTypes,
		MessageInfos:      file_proto_models_dialectic_proto_msgTypes,
	}.Build()
	File_proto_models_dialectic_proto = out.File
	file_proto_models_dialectic_proto_rawDesc = nil
	file_proto_models_dialectic_proto_goTypes = nil
	file_proto_models_dialectic_proto_depIdxs = nil
}
