// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/epistemic_me.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	pb "epistemic-me-backend/pb"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EpistemicMeServiceName is the fully-qualified name of the EpistemicMeService service.
	EpistemicMeServiceName = "EpistemicMeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EpistemicMeServiceCreateBeliefProcedure is the fully-qualified name of the EpistemicMeService's
	// CreateBelief RPC.
	EpistemicMeServiceCreateBeliefProcedure = "/EpistemicMeService/CreateBelief"
	// EpistemicMeServiceListBeliefsProcedure is the fully-qualified name of the EpistemicMeService's
	// ListBeliefs RPC.
	EpistemicMeServiceListBeliefsProcedure = "/EpistemicMeService/ListBeliefs"
	// EpistemicMeServiceCreateDialecticProcedure is the fully-qualified name of the
	// EpistemicMeService's CreateDialectic RPC.
	EpistemicMeServiceCreateDialecticProcedure = "/EpistemicMeService/CreateDialectic"
	// EpistemicMeServiceListDialecticsProcedure is the fully-qualified name of the EpistemicMeService's
	// ListDialectics RPC.
	EpistemicMeServiceListDialecticsProcedure = "/EpistemicMeService/ListDialectics"
	// EpistemicMeServiceUpdateDialecticProcedure is the fully-qualified name of the
	// EpistemicMeService's UpdateDialectic RPC.
	EpistemicMeServiceUpdateDialecticProcedure = "/EpistemicMeService/UpdateDialectic"
	// EpistemicMeServiceGetBeliefSystemProcedure is the fully-qualified name of the
	// EpistemicMeService's GetBeliefSystem RPC.
	EpistemicMeServiceGetBeliefSystemProcedure = "/EpistemicMeService/GetBeliefSystem"
	// EpistemicMeServiceUpdateKeyValueStoreProcedure is the fully-qualified name of the
	// EpistemicMeService's UpdateKeyValueStore RPC.
	EpistemicMeServiceUpdateKeyValueStoreProcedure = "/EpistemicMeService/UpdateKeyValueStore"
	// EpistemicMeServiceCreateSelfModelProcedure is the fully-qualified name of the
	// EpistemicMeService's CreateSelfModel RPC.
	EpistemicMeServiceCreateSelfModelProcedure = "/EpistemicMeService/CreateSelfModel"
	// EpistemicMeServiceGetSelfModelProcedure is the fully-qualified name of the EpistemicMeService's
	// GetSelfModel RPC.
	EpistemicMeServiceGetSelfModelProcedure = "/EpistemicMeService/GetSelfModel"
	// EpistemicMeServiceAddPhilosophyProcedure is the fully-qualified name of the EpistemicMeService's
	// AddPhilosophy RPC.
	EpistemicMeServiceAddPhilosophyProcedure = "/EpistemicMeService/AddPhilosophy"
	// EpistemicMeServiceCreateDeveloperProcedure is the fully-qualified name of the
	// EpistemicMeService's CreateDeveloper RPC.
	EpistemicMeServiceCreateDeveloperProcedure = "/EpistemicMeService/CreateDeveloper"
	// EpistemicMeServiceCreateUserProcedure is the fully-qualified name of the EpistemicMeService's
	// CreateUser RPC.
	EpistemicMeServiceCreateUserProcedure = "/EpistemicMeService/CreateUser"
	// EpistemicMeServiceGetDeveloperProcedure is the fully-qualified name of the EpistemicMeService's
	// GetDeveloper RPC.
	EpistemicMeServiceGetDeveloperProcedure = "/EpistemicMeService/GetDeveloper"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	epistemicMeServiceServiceDescriptor                   = pb.File_proto_epistemic_me_proto.Services().ByName("EpistemicMeService")
	epistemicMeServiceCreateBeliefMethodDescriptor        = epistemicMeServiceServiceDescriptor.Methods().ByName("CreateBelief")
	epistemicMeServiceListBeliefsMethodDescriptor         = epistemicMeServiceServiceDescriptor.Methods().ByName("ListBeliefs")
	epistemicMeServiceCreateDialecticMethodDescriptor     = epistemicMeServiceServiceDescriptor.Methods().ByName("CreateDialectic")
	epistemicMeServiceListDialecticsMethodDescriptor      = epistemicMeServiceServiceDescriptor.Methods().ByName("ListDialectics")
	epistemicMeServiceUpdateDialecticMethodDescriptor     = epistemicMeServiceServiceDescriptor.Methods().ByName("UpdateDialectic")
	epistemicMeServiceGetBeliefSystemMethodDescriptor     = epistemicMeServiceServiceDescriptor.Methods().ByName("GetBeliefSystem")
	epistemicMeServiceUpdateKeyValueStoreMethodDescriptor = epistemicMeServiceServiceDescriptor.Methods().ByName("UpdateKeyValueStore")
	epistemicMeServiceCreateSelfModelMethodDescriptor     = epistemicMeServiceServiceDescriptor.Methods().ByName("CreateSelfModel")
	epistemicMeServiceGetSelfModelMethodDescriptor        = epistemicMeServiceServiceDescriptor.Methods().ByName("GetSelfModel")
	epistemicMeServiceAddPhilosophyMethodDescriptor       = epistemicMeServiceServiceDescriptor.Methods().ByName("AddPhilosophy")
	epistemicMeServiceCreateDeveloperMethodDescriptor     = epistemicMeServiceServiceDescriptor.Methods().ByName("CreateDeveloper")
	epistemicMeServiceCreateUserMethodDescriptor          = epistemicMeServiceServiceDescriptor.Methods().ByName("CreateUser")
	epistemicMeServiceGetDeveloperMethodDescriptor        = epistemicMeServiceServiceDescriptor.Methods().ByName("GetDeveloper")
)

// EpistemicMeServiceClient is a client for the EpistemicMeService service.
type EpistemicMeServiceClient interface {
	CreateBelief(context.Context, *connect.Request[pb.CreateBeliefRequest]) (*connect.Response[pb.CreateBeliefResponse], error)
	ListBeliefs(context.Context, *connect.Request[pb.ListBeliefsRequest]) (*connect.Response[pb.ListBeliefsResponse], error)
	CreateDialectic(context.Context, *connect.Request[pb.CreateDialecticRequest]) (*connect.Response[pb.CreateDialecticResponse], error)
	ListDialectics(context.Context, *connect.Request[pb.ListDialecticsRequest]) (*connect.Response[pb.ListDialecticsResponse], error)
	UpdateDialectic(context.Context, *connect.Request[pb.UpdateDialecticRequest]) (*connect.Response[pb.UpdateDialecticResponse], error)
	GetBeliefSystem(context.Context, *connect.Request[pb.GetBeliefSystemRequest]) (*connect.Response[pb.GetBeliefSystemResponse], error)
	UpdateKeyValueStore(context.Context, *connect.Request[pb.UpdateKeyValueStoreRequest]) (*connect.Response[pb.UpdateKeyValueStoreResponse], error)
	CreateSelfModel(context.Context, *connect.Request[pb.CreateSelfModelRequest]) (*connect.Response[pb.CreateSelfModelResponse], error)
	GetSelfModel(context.Context, *connect.Request[pb.GetSelfModelRequest]) (*connect.Response[pb.GetSelfModelResponse], error)
	AddPhilosophy(context.Context, *connect.Request[pb.AddPhilosophyRequest]) (*connect.Response[pb.AddPhilosophyResponse], error)
	CreateDeveloper(context.Context, *connect.Request[pb.CreateDeveloperRequest]) (*connect.Response[pb.CreateDeveloperResponse], error)
	CreateUser(context.Context, *connect.Request[pb.CreateUserRequest]) (*connect.Response[pb.CreateUserResponse], error)
	GetDeveloper(context.Context, *connect.Request[pb.GetDeveloperRequest]) (*connect.Response[pb.GetDeveloperResponse], error)
}

// NewEpistemicMeServiceClient constructs a client for the EpistemicMeService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEpistemicMeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EpistemicMeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &epistemicMeServiceClient{
		createBelief: connect.NewClient[pb.CreateBeliefRequest, pb.CreateBeliefResponse](
			httpClient,
			baseURL+EpistemicMeServiceCreateBeliefProcedure,
			connect.WithSchema(epistemicMeServiceCreateBeliefMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listBeliefs: connect.NewClient[pb.ListBeliefsRequest, pb.ListBeliefsResponse](
			httpClient,
			baseURL+EpistemicMeServiceListBeliefsProcedure,
			connect.WithSchema(epistemicMeServiceListBeliefsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createDialectic: connect.NewClient[pb.CreateDialecticRequest, pb.CreateDialecticResponse](
			httpClient,
			baseURL+EpistemicMeServiceCreateDialecticProcedure,
			connect.WithSchema(epistemicMeServiceCreateDialecticMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listDialectics: connect.NewClient[pb.ListDialecticsRequest, pb.ListDialecticsResponse](
			httpClient,
			baseURL+EpistemicMeServiceListDialecticsProcedure,
			connect.WithSchema(epistemicMeServiceListDialecticsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updateDialectic: connect.NewClient[pb.UpdateDialecticRequest, pb.UpdateDialecticResponse](
			httpClient,
			baseURL+EpistemicMeServiceUpdateDialecticProcedure,
			connect.WithSchema(epistemicMeServiceUpdateDialecticMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getBeliefSystem: connect.NewClient[pb.GetBeliefSystemRequest, pb.GetBeliefSystemResponse](
			httpClient,
			baseURL+EpistemicMeServiceGetBeliefSystemProcedure,
			connect.WithSchema(epistemicMeServiceGetBeliefSystemMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updateKeyValueStore: connect.NewClient[pb.UpdateKeyValueStoreRequest, pb.UpdateKeyValueStoreResponse](
			httpClient,
			baseURL+EpistemicMeServiceUpdateKeyValueStoreProcedure,
			connect.WithSchema(epistemicMeServiceUpdateKeyValueStoreMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createSelfModel: connect.NewClient[pb.CreateSelfModelRequest, pb.CreateSelfModelResponse](
			httpClient,
			baseURL+EpistemicMeServiceCreateSelfModelProcedure,
			connect.WithSchema(epistemicMeServiceCreateSelfModelMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getSelfModel: connect.NewClient[pb.GetSelfModelRequest, pb.GetSelfModelResponse](
			httpClient,
			baseURL+EpistemicMeServiceGetSelfModelProcedure,
			connect.WithSchema(epistemicMeServiceGetSelfModelMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		addPhilosophy: connect.NewClient[pb.AddPhilosophyRequest, pb.AddPhilosophyResponse](
			httpClient,
			baseURL+EpistemicMeServiceAddPhilosophyProcedure,
			connect.WithSchema(epistemicMeServiceAddPhilosophyMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createDeveloper: connect.NewClient[pb.CreateDeveloperRequest, pb.CreateDeveloperResponse](
			httpClient,
			baseURL+EpistemicMeServiceCreateDeveloperProcedure,
			connect.WithSchema(epistemicMeServiceCreateDeveloperMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createUser: connect.NewClient[pb.CreateUserRequest, pb.CreateUserResponse](
			httpClient,
			baseURL+EpistemicMeServiceCreateUserProcedure,
			connect.WithSchema(epistemicMeServiceCreateUserMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getDeveloper: connect.NewClient[pb.GetDeveloperRequest, pb.GetDeveloperResponse](
			httpClient,
			baseURL+EpistemicMeServiceGetDeveloperProcedure,
			connect.WithSchema(epistemicMeServiceGetDeveloperMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// epistemicMeServiceClient implements EpistemicMeServiceClient.
type epistemicMeServiceClient struct {
	createBelief        *connect.Client[pb.CreateBeliefRequest, pb.CreateBeliefResponse]
	listBeliefs         *connect.Client[pb.ListBeliefsRequest, pb.ListBeliefsResponse]
	createDialectic     *connect.Client[pb.CreateDialecticRequest, pb.CreateDialecticResponse]
	listDialectics      *connect.Client[pb.ListDialecticsRequest, pb.ListDialecticsResponse]
	updateDialectic     *connect.Client[pb.UpdateDialecticRequest, pb.UpdateDialecticResponse]
	getBeliefSystem     *connect.Client[pb.GetBeliefSystemRequest, pb.GetBeliefSystemResponse]
	updateKeyValueStore *connect.Client[pb.UpdateKeyValueStoreRequest, pb.UpdateKeyValueStoreResponse]
	createSelfModel     *connect.Client[pb.CreateSelfModelRequest, pb.CreateSelfModelResponse]
	getSelfModel        *connect.Client[pb.GetSelfModelRequest, pb.GetSelfModelResponse]
	addPhilosophy       *connect.Client[pb.AddPhilosophyRequest, pb.AddPhilosophyResponse]
	createDeveloper     *connect.Client[pb.CreateDeveloperRequest, pb.CreateDeveloperResponse]
	createUser          *connect.Client[pb.CreateUserRequest, pb.CreateUserResponse]
	getDeveloper        *connect.Client[pb.GetDeveloperRequest, pb.GetDeveloperResponse]
}

// CreateBelief calls EpistemicMeService.CreateBelief.
func (c *epistemicMeServiceClient) CreateBelief(ctx context.Context, req *connect.Request[pb.CreateBeliefRequest]) (*connect.Response[pb.CreateBeliefResponse], error) {
	return c.createBelief.CallUnary(ctx, req)
}

// ListBeliefs calls EpistemicMeService.ListBeliefs.
func (c *epistemicMeServiceClient) ListBeliefs(ctx context.Context, req *connect.Request[pb.ListBeliefsRequest]) (*connect.Response[pb.ListBeliefsResponse], error) {
	return c.listBeliefs.CallUnary(ctx, req)
}

// CreateDialectic calls EpistemicMeService.CreateDialectic.
func (c *epistemicMeServiceClient) CreateDialectic(ctx context.Context, req *connect.Request[pb.CreateDialecticRequest]) (*connect.Response[pb.CreateDialecticResponse], error) {
	return c.createDialectic.CallUnary(ctx, req)
}

// ListDialectics calls EpistemicMeService.ListDialectics.
func (c *epistemicMeServiceClient) ListDialectics(ctx context.Context, req *connect.Request[pb.ListDialecticsRequest]) (*connect.Response[pb.ListDialecticsResponse], error) {
	return c.listDialectics.CallUnary(ctx, req)
}

// UpdateDialectic calls EpistemicMeService.UpdateDialectic.
func (c *epistemicMeServiceClient) UpdateDialectic(ctx context.Context, req *connect.Request[pb.UpdateDialecticRequest]) (*connect.Response[pb.UpdateDialecticResponse], error) {
	return c.updateDialectic.CallUnary(ctx, req)
}

// GetBeliefSystem calls EpistemicMeService.GetBeliefSystem.
func (c *epistemicMeServiceClient) GetBeliefSystem(ctx context.Context, req *connect.Request[pb.GetBeliefSystemRequest]) (*connect.Response[pb.GetBeliefSystemResponse], error) {
	return c.getBeliefSystem.CallUnary(ctx, req)
}

// UpdateKeyValueStore calls EpistemicMeService.UpdateKeyValueStore.
func (c *epistemicMeServiceClient) UpdateKeyValueStore(ctx context.Context, req *connect.Request[pb.UpdateKeyValueStoreRequest]) (*connect.Response[pb.UpdateKeyValueStoreResponse], error) {
	return c.updateKeyValueStore.CallUnary(ctx, req)
}

// CreateSelfModel calls EpistemicMeService.CreateSelfModel.
func (c *epistemicMeServiceClient) CreateSelfModel(ctx context.Context, req *connect.Request[pb.CreateSelfModelRequest]) (*connect.Response[pb.CreateSelfModelResponse], error) {
	return c.createSelfModel.CallUnary(ctx, req)
}

// GetSelfModel calls EpistemicMeService.GetSelfModel.
func (c *epistemicMeServiceClient) GetSelfModel(ctx context.Context, req *connect.Request[pb.GetSelfModelRequest]) (*connect.Response[pb.GetSelfModelResponse], error) {
	return c.getSelfModel.CallUnary(ctx, req)
}

// AddPhilosophy calls EpistemicMeService.AddPhilosophy.
func (c *epistemicMeServiceClient) AddPhilosophy(ctx context.Context, req *connect.Request[pb.AddPhilosophyRequest]) (*connect.Response[pb.AddPhilosophyResponse], error) {
	return c.addPhilosophy.CallUnary(ctx, req)
}

// CreateDeveloper calls EpistemicMeService.CreateDeveloper.
func (c *epistemicMeServiceClient) CreateDeveloper(ctx context.Context, req *connect.Request[pb.CreateDeveloperRequest]) (*connect.Response[pb.CreateDeveloperResponse], error) {
	return c.createDeveloper.CallUnary(ctx, req)
}

// CreateUser calls EpistemicMeService.CreateUser.
func (c *epistemicMeServiceClient) CreateUser(ctx context.Context, req *connect.Request[pb.CreateUserRequest]) (*connect.Response[pb.CreateUserResponse], error) {
	return c.createUser.CallUnary(ctx, req)
}

// GetDeveloper calls EpistemicMeService.GetDeveloper.
func (c *epistemicMeServiceClient) GetDeveloper(ctx context.Context, req *connect.Request[pb.GetDeveloperRequest]) (*connect.Response[pb.GetDeveloperResponse], error) {
	return c.getDeveloper.CallUnary(ctx, req)
}

// EpistemicMeServiceHandler is an implementation of the EpistemicMeService service.
type EpistemicMeServiceHandler interface {
	CreateBelief(context.Context, *connect.Request[pb.CreateBeliefRequest]) (*connect.Response[pb.CreateBeliefResponse], error)
	ListBeliefs(context.Context, *connect.Request[pb.ListBeliefsRequest]) (*connect.Response[pb.ListBeliefsResponse], error)
	CreateDialectic(context.Context, *connect.Request[pb.CreateDialecticRequest]) (*connect.Response[pb.CreateDialecticResponse], error)
	ListDialectics(context.Context, *connect.Request[pb.ListDialecticsRequest]) (*connect.Response[pb.ListDialecticsResponse], error)
	UpdateDialectic(context.Context, *connect.Request[pb.UpdateDialecticRequest]) (*connect.Response[pb.UpdateDialecticResponse], error)
	GetBeliefSystem(context.Context, *connect.Request[pb.GetBeliefSystemRequest]) (*connect.Response[pb.GetBeliefSystemResponse], error)
	UpdateKeyValueStore(context.Context, *connect.Request[pb.UpdateKeyValueStoreRequest]) (*connect.Response[pb.UpdateKeyValueStoreResponse], error)
	CreateSelfModel(context.Context, *connect.Request[pb.CreateSelfModelRequest]) (*connect.Response[pb.CreateSelfModelResponse], error)
	GetSelfModel(context.Context, *connect.Request[pb.GetSelfModelRequest]) (*connect.Response[pb.GetSelfModelResponse], error)
	AddPhilosophy(context.Context, *connect.Request[pb.AddPhilosophyRequest]) (*connect.Response[pb.AddPhilosophyResponse], error)
	CreateDeveloper(context.Context, *connect.Request[pb.CreateDeveloperRequest]) (*connect.Response[pb.CreateDeveloperResponse], error)
	CreateUser(context.Context, *connect.Request[pb.CreateUserRequest]) (*connect.Response[pb.CreateUserResponse], error)
	GetDeveloper(context.Context, *connect.Request[pb.GetDeveloperRequest]) (*connect.Response[pb.GetDeveloperResponse], error)
}

// NewEpistemicMeServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEpistemicMeServiceHandler(svc EpistemicMeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	epistemicMeServiceCreateBeliefHandler := connect.NewUnaryHandler(
		EpistemicMeServiceCreateBeliefProcedure,
		svc.CreateBelief,
		connect.WithSchema(epistemicMeServiceCreateBeliefMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	epistemicMeServiceListBeliefsHandler := connect.NewUnaryHandler(
		EpistemicMeServiceListBeliefsProcedure,
		svc.ListBeliefs,
		connect.WithSchema(epistemicMeServiceListBeliefsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	epistemicMeServiceCreateDialecticHandler := connect.NewUnaryHandler(
		EpistemicMeServiceCreateDialecticProcedure,
		svc.CreateDialectic,
		connect.WithSchema(epistemicMeServiceCreateDialecticMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	epistemicMeServiceListDialecticsHandler := connect.NewUnaryHandler(
		EpistemicMeServiceListDialecticsProcedure,
		svc.ListDialectics,
		connect.WithSchema(epistemicMeServiceListDialecticsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	epistemicMeServiceUpdateDialecticHandler := connect.NewUnaryHandler(
		EpistemicMeServiceUpdateDialecticProcedure,
		svc.UpdateDialectic,
		connect.WithSchema(epistemicMeServiceUpdateDialecticMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	epistemicMeServiceGetBeliefSystemHandler := connect.NewUnaryHandler(
		EpistemicMeServiceGetBeliefSystemProcedure,
		svc.GetBeliefSystem,
		connect.WithSchema(epistemicMeServiceGetBeliefSystemMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	epistemicMeServiceUpdateKeyValueStoreHandler := connect.NewUnaryHandler(
		EpistemicMeServiceUpdateKeyValueStoreProcedure,
		svc.UpdateKeyValueStore,
		connect.WithSchema(epistemicMeServiceUpdateKeyValueStoreMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	epistemicMeServiceCreateSelfModelHandler := connect.NewUnaryHandler(
		EpistemicMeServiceCreateSelfModelProcedure,
		svc.CreateSelfModel,
		connect.WithSchema(epistemicMeServiceCreateSelfModelMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	epistemicMeServiceGetSelfModelHandler := connect.NewUnaryHandler(
		EpistemicMeServiceGetSelfModelProcedure,
		svc.GetSelfModel,
		connect.WithSchema(epistemicMeServiceGetSelfModelMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	epistemicMeServiceAddPhilosophyHandler := connect.NewUnaryHandler(
		EpistemicMeServiceAddPhilosophyProcedure,
		svc.AddPhilosophy,
		connect.WithSchema(epistemicMeServiceAddPhilosophyMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	epistemicMeServiceCreateDeveloperHandler := connect.NewUnaryHandler(
		EpistemicMeServiceCreateDeveloperProcedure,
		svc.CreateDeveloper,
		connect.WithSchema(epistemicMeServiceCreateDeveloperMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	epistemicMeServiceCreateUserHandler := connect.NewUnaryHandler(
		EpistemicMeServiceCreateUserProcedure,
		svc.CreateUser,
		connect.WithSchema(epistemicMeServiceCreateUserMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	epistemicMeServiceGetDeveloperHandler := connect.NewUnaryHandler(
		EpistemicMeServiceGetDeveloperProcedure,
		svc.GetDeveloper,
		connect.WithSchema(epistemicMeServiceGetDeveloperMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/EpistemicMeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EpistemicMeServiceCreateBeliefProcedure:
			epistemicMeServiceCreateBeliefHandler.ServeHTTP(w, r)
		case EpistemicMeServiceListBeliefsProcedure:
			epistemicMeServiceListBeliefsHandler.ServeHTTP(w, r)
		case EpistemicMeServiceCreateDialecticProcedure:
			epistemicMeServiceCreateDialecticHandler.ServeHTTP(w, r)
		case EpistemicMeServiceListDialecticsProcedure:
			epistemicMeServiceListDialecticsHandler.ServeHTTP(w, r)
		case EpistemicMeServiceUpdateDialecticProcedure:
			epistemicMeServiceUpdateDialecticHandler.ServeHTTP(w, r)
		case EpistemicMeServiceGetBeliefSystemProcedure:
			epistemicMeServiceGetBeliefSystemHandler.ServeHTTP(w, r)
		case EpistemicMeServiceUpdateKeyValueStoreProcedure:
			epistemicMeServiceUpdateKeyValueStoreHandler.ServeHTTP(w, r)
		case EpistemicMeServiceCreateSelfModelProcedure:
			epistemicMeServiceCreateSelfModelHandler.ServeHTTP(w, r)
		case EpistemicMeServiceGetSelfModelProcedure:
			epistemicMeServiceGetSelfModelHandler.ServeHTTP(w, r)
		case EpistemicMeServiceAddPhilosophyProcedure:
			epistemicMeServiceAddPhilosophyHandler.ServeHTTP(w, r)
		case EpistemicMeServiceCreateDeveloperProcedure:
			epistemicMeServiceCreateDeveloperHandler.ServeHTTP(w, r)
		case EpistemicMeServiceCreateUserProcedure:
			epistemicMeServiceCreateUserHandler.ServeHTTP(w, r)
		case EpistemicMeServiceGetDeveloperProcedure:
			epistemicMeServiceGetDeveloperHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEpistemicMeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEpistemicMeServiceHandler struct{}

func (UnimplementedEpistemicMeServiceHandler) CreateBelief(context.Context, *connect.Request[pb.CreateBeliefRequest]) (*connect.Response[pb.CreateBeliefResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("EpistemicMeService.CreateBelief is not implemented"))
}

func (UnimplementedEpistemicMeServiceHandler) ListBeliefs(context.Context, *connect.Request[pb.ListBeliefsRequest]) (*connect.Response[pb.ListBeliefsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("EpistemicMeService.ListBeliefs is not implemented"))
}

func (UnimplementedEpistemicMeServiceHandler) CreateDialectic(context.Context, *connect.Request[pb.CreateDialecticRequest]) (*connect.Response[pb.CreateDialecticResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("EpistemicMeService.CreateDialectic is not implemented"))
}

func (UnimplementedEpistemicMeServiceHandler) ListDialectics(context.Context, *connect.Request[pb.ListDialecticsRequest]) (*connect.Response[pb.ListDialecticsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("EpistemicMeService.ListDialectics is not implemented"))
}

func (UnimplementedEpistemicMeServiceHandler) UpdateDialectic(context.Context, *connect.Request[pb.UpdateDialecticRequest]) (*connect.Response[pb.UpdateDialecticResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("EpistemicMeService.UpdateDialectic is not implemented"))
}

func (UnimplementedEpistemicMeServiceHandler) GetBeliefSystem(context.Context, *connect.Request[pb.GetBeliefSystemRequest]) (*connect.Response[pb.GetBeliefSystemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("EpistemicMeService.GetBeliefSystem is not implemented"))
}

func (UnimplementedEpistemicMeServiceHandler) UpdateKeyValueStore(context.Context, *connect.Request[pb.UpdateKeyValueStoreRequest]) (*connect.Response[pb.UpdateKeyValueStoreResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("EpistemicMeService.UpdateKeyValueStore is not implemented"))
}

func (UnimplementedEpistemicMeServiceHandler) CreateSelfModel(context.Context, *connect.Request[pb.CreateSelfModelRequest]) (*connect.Response[pb.CreateSelfModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("EpistemicMeService.CreateSelfModel is not implemented"))
}

func (UnimplementedEpistemicMeServiceHandler) GetSelfModel(context.Context, *connect.Request[pb.GetSelfModelRequest]) (*connect.Response[pb.GetSelfModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("EpistemicMeService.GetSelfModel is not implemented"))
}

func (UnimplementedEpistemicMeServiceHandler) AddPhilosophy(context.Context, *connect.Request[pb.AddPhilosophyRequest]) (*connect.Response[pb.AddPhilosophyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("EpistemicMeService.AddPhilosophy is not implemented"))
}

func (UnimplementedEpistemicMeServiceHandler) CreateDeveloper(context.Context, *connect.Request[pb.CreateDeveloperRequest]) (*connect.Response[pb.CreateDeveloperResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("EpistemicMeService.CreateDeveloper is not implemented"))
}

func (UnimplementedEpistemicMeServiceHandler) CreateUser(context.Context, *connect.Request[pb.CreateUserRequest]) (*connect.Response[pb.CreateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("EpistemicMeService.CreateUser is not implemented"))
}

func (UnimplementedEpistemicMeServiceHandler) GetDeveloper(context.Context, *connect.Request[pb.GetDeveloperRequest]) (*connect.Response[pb.GetDeveloperResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("EpistemicMeService.GetDeveloper is not implemented"))
}
