interventions: [
  {
    id: 1
    name: "drinking water"
    description: "Drinking water upon waking."
  },
  {
    id: 2
    name: "exercise"
    description: "Engaging in daily physical exercise."
  }
]

habits: [
  {
    id: 1
    name: "Drink Water Upon Waking"
    intervention_id: 1
    intervention_name: "drinking water"
    causal_belief_id: "1"
    causal_belief_description: "If I drink water, I will have more mental clarity."
    description: "Drinking water upon waking will improve hydration and mental clarity throughout the day."
  },
  {
    id: 2
    name: "Exercise Daily"
    intervention_id: 2
    intervention_name: "exercise"
    causal_belief_id: "2"
    causal_belief_description: "Daily exercise will increase overall energy levels and improve mood."
    description: "Daily exercise will increase overall energy levels and improve mood."
  }
]
