sources: [
  {
    name: "Observation Result from Mental Clarity"
    type: OBSERVATION_CONTEXT
    observation_context_id: 2
  },
  {
    name: "Observation Result from Energy Levels"
    type: OBSERVATION_CONTEXT
    observation_context_id: 3
  },
  {
    name: "Plato's Republic"
    type: AUTHORITY
    resources: [
      {
        name: "Plato's Republic"
        type: BOOK
      }
    ]
  },
  {
    name: "Hydration Study 2021"
    type: AUTHORITY
    resources: [
      {
        name: "Hydration Study 2021"
        type: SCIENTIFIC_RESULT
      }
    ]
  },
  {
    name: "Mental Clarity Research 2021"
    type: AUTHORITY
    resources: [
      {
        name: "Mental Clarity Research 2021"
        type: SCIENTIFIC_RESULT
      }
    ]
  },
  {
    name: "Energy Study 2021"
    type: AUTHORITY
    resources: [
      {
        name: "Energy Study 2021"
        type: SCIENTIFIC_RESULT
      }
    ]
  }
]
